### ISSUE TITLE
How does it works?

### ISSUE THREAD

**Issue by BlackIQ** [amirshnll/useslist#1]
سلام.

ایده این ریپوزیتوری این هست که کاربران برای مثال فورک کنند و نرم افزار یا سخت افزار هایی که روزمره استفاده میکنند رو اضافه کنند؟
یا مثل پروژه [rtbf](https://github.com/amirshnll/rtbf.ir) نیاز هست که ایشو باز کنیم؟

بعد به صورت تحت وب باز میشه این پروژه ها مثلا با md درست میشه؟

یا کلا این موضوع نیست!؟

**Comment by amirshnll** [comment]
در حال کار روی پروژه هستم ایده بخش اول صحبت هات هست یکم صبر :)

**Comment by BlackIQ** [comment]
ایول. مرسی. تشکر.
این ایشو نیاز هست بسته بشه یا باز باشه؟

**Comment by BlackIQ** [comment]
و این که اگه کمکی از دست بنده بر میاد بفرمایید. خوشحال میشم کمک کنم.

**Comment by amirshnll** [comment]
اگر صبر کنی من یه نسخه از کاری که میخوام رو انجام بدم بیارم بالا بعد مطالعه کن اگر دوست داشتی اره چرا که چیزی که خواستی یا لازم بود رو اضافه کن مرسی
